db:
#  url: jdbc:postgresql://localhost:5432/flight_repository
  url: jdbc:postgresql://localhost:5432/postgres
  username: ${username.value:postgres}
  password: postgres
  driver: PostgresDriver
  hosts: localhost,127.0.0.1
#  default_schema: tables1
  properties:
    first: 123
    second: 456
    third.value: Third
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

spring.profiles.active: qa

logging:
  level:
    root: INFO
    com.svtsygankov.spring.database.pool.ConnectionPool: INFO
    org.springframework.jdbc.core: TRACE
  file:
    name: svtsygankov.log
    path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
#    default_schema: tables1
  jpa:
    properties.hibernate:
        batch_size: 50
        fetch_size: 50
        show_sql: true
        format_sql: true
        hbm2ddl.auto: validate
#        default_schema: tables1
